# Generated by Django 3.2.4 on 2022-01-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='formacion')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('objetivo_th1', models.CharField(max_length=50)),
                ('habilidAdq_th2', models.CharField(max_length=50)),
                ('td', models.JSONField(decoder=str)),
                ('competencias', models.CharField(max_length=50)),
                ('li', models.JSONField(decoder=str)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'formacion',
                'verbose_name_plural': 'formaciones',
            },
        ),
    ]
