# Generated by Django 3.2.4 on 2022-01-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacion',
            name='li',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='formacion',
            name='td',
            field=models.JSONField(),
        ),
    ]
